site_name: Docs
site_url: https://mazharul419.github.io/ECS-Forge/

docs_dir: docs

nav:
  - Architectural Decisions: Architectural_Decisions.md
  - Documentation: Documentation.md
  - Diagram: ecs-architecture-diagram.html

theme:
  name: material
  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  features:
    - navigation.footer
    - content.code.annotate 
markdown_extensions:
  - md_in_html
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets:
      base_path: . 
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details

plugins:
  - search

extra_css:
  - stylesheets/extra.css