name: Lint Terragrunt Code (Automatic)

on:
  push:
    branches: [main]

env:
  AWS_REGION: eu-west-2
  TERRAGRUNT_VERSION: 0.93.13
  TERRAFORM_VERSION: 1.14.1
  ASDF_TERRAGRUNT_SKIP_CHECKSUM: "true"
  TF_VAR_cloudflare_api_token: ${{ secrets.TF_VAR_cloudflare_api_token }}

permissions:
  id-token: write
  contents: read

jobs:
  Dev:
    name: Dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-role
          aws-region: ${{ env.AWS_REGION }}
          role-duration-seconds: 3600

      - name: Create common.hcl
        run: |
          mkdir -p $GITHUB_WORKSPACE/infrastructure/live/_env
          cat > $GITHUB_WORKSPACE/infrastructure/live/_env/common.hcl <<EOF
          locals {
            container_port     = 8080
            domain_name        = "mazharulislam.dev"
            cloudflare_zone_id = "${{ secrets.CLOUDFLARE_ZONE_ID }}"
          }
          EOF

      - name: Set working directory
        id: set-dir
        run: |
            echo "dir=$GITHUB_WORKSPACE/infrastructure/live/dev" >> $GITHUB_OUTPUT

      - name: Print working directory
        run: echo ${{ steps.set-dir.outputs.dir }}

      - name: Terragrunt Init Dev
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tf_version: ${{ env.TERRAFORM_VERSION }}
          tg_version: ${{ env.TERRAGRUNT_VERSION }}
          tg_dir: ${{ steps.set-dir.outputs.dir }}
          tg_command: run --all init
          tg_cli_args: --non-interactive

      - name: Terragrunt Validate Dev
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tf_version: ${{ env.TERRAFORM_VERSION }}
          tg_version: ${{ env.TERRAGRUNT_VERSION }}
          tg_dir: ${{ steps.set-dir.outputs.dir }}
          tg_command: run --all validate
          tg_cli_args: --non-interactive

      - name: Terragrunt Format Dev
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tf_version: ${{ env.TERRAFORM_VERSION }}
          tg_version: ${{ env.TERRAGRUNT_VERSION }}
          tg_dir: ${{ steps.set-dir.outputs.dir }}
          tg_command: hcl format --check --diff
          tg_cli_args: --non-interactive

      - name: Dev Summary
        if: always()
        run: |
          echo "### Terragrunt Dev linting Complete" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Directory**: $GITHUB_WORKSPACE/infrastructure/live/dev" >> $GITHUB_STEP_SUMMARY
          echo "- **Status**: ${{ job.status }}" >> $GITHUB_STEP_SUMMARY

  Prod:
    name: Prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-role
          aws-region: ${{ env.AWS_REGION }}
          role-duration-seconds: 3600

      - name: Create common.hcl
        run: |
          mkdir -p $GITHUB_WORKSPACE/infrastructure/live/_env
          cat > $GITHUB_WORKSPACE/infrastructure/live/_env/common.hcl <<EOF
          locals {
            container_port     = 8080
            domain_name        = "mazharulislam.dev"
            cloudflare_zone_id = "${{ secrets.CLOUDFLARE_ZONE_ID }}"
          }
          EOF

      - name: Set working directory
        id: set-dir
        run: |
            echo "dir=$GITHUB_WORKSPACE/infrastructure/live/prod" >> $GITHUB_OUTPUT

      - name: Print working directory
        run: echo ${{ steps.set-dir.outputs.dir }}

      - name: Terragrunt Init Prod
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tf_version: ${{ env.TERRAFORM_VERSION }}
          tg_version: ${{ env.TERRAGRUNT_VERSION }}
          tg_dir: ${{ steps.set-dir.outputs.dir }}
          tg_command: run --all init
          tg_cli_args: --non-interactive

      - name: Terragrunt Validate Prod
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tf_version: ${{ env.TERRAFORM_VERSION }}
          tg_version: ${{ env.TERRAGRUNT_VERSION }}
          tg_dir: ${{ steps.set-dir.outputs.dir }}
          tg_command: run --all validate
          tg_cli_args: --non-interactive

      - name: Terragrunt Format Prod
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tf_version: ${{ env.TERRAFORM_VERSION }}
          tg_version: ${{ env.TERRAGRUNT_VERSION }}
          tg_dir: ${{ steps.set-dir.outputs.dir }}
          tg_command: hcl format --check --diff
          tg_cli_args: --non-interactive

      - name: Prod Summary
        if: always()
        run: |
          echo "### Terragrunt Prod linting Complete" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Action**: ${{ inputs.action }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Directory**: $GITHUB_WORKSPACE/infrastructure/live/prod" >> $GITHUB_STEP_SUMMARY
          echo "- **Status**: ${{ job.status }}" >> $GITHUB_STEP_SUMMARY